version: "3"

services:

  mysqldb:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - 3307:3306

  app:
    build:
      context: .
    hostname: app
    env_file:
      - .env
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"

volumes:
  mysql:
  mysql_config: