version: "3"

services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    hostname: db
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - 3307:3306

  app:
    build:
      context: .
    hostname: app
    env_file:
      - .env
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"

volumes:
  mysql:
  mysql_config: